# Generated by Django 5.2.13 on 2026-05-02 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-registered_at'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companymembership',
            options={'ordering': ['company', 'role']},
        ),
        migrations.AlterModelOptions(
            name='dataentry',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stockitem2',
            options={'ordering': ['stock_name']},
        ),
        migrations.AlterModelOptions(
            name='stockrestock',
            options={'ordering': ['-restock_date']},
        ),
        migrations.AlterModelOptions(
            name='userentry',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='userentry2',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='userentryexpense',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='userentryoutofstock',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='stockitem',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost to acquire one unit of this stock.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at which one unit is sold to customers.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem2',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost to acquire one sqm of this stock.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem2',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at which one sqm is sold to customers.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='companymembership',
            unique_together={('user', 'company')},
        ),
    ]
